version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017    
    
    volumes:
      - mongo-volume:/data/db
  
  web:
    build: ./flask
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  mongo-volume:
    external: true  # if volume with this name exists,  it will not create a new one with "folder" prefix.