version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017    
    
    volumes:
      - mongodb_data:/data/db
  
  web:
    build: ./flask
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  mongodb_data: